### ISSUE TITLE
update resource tarball to v1.5.3 release

### ISSUE THREAD

**Issue by dpark01** [dnanexus/viral-ngs#11]
this fixes a few bugs that we've noticed, particularly with the handling of empty bam files at various points in depletion, metagenomics, and assembly

**Comment by dpark01** [comment]
Ugh, sorry, I keep finding little bugs. This should be the last one. v1.5.3 doesn't exist yet.. still running tests on the PR and will tag once it's merged in today

**Comment by dpark01** [comment]
v1.5.3 is in and ready

**Comment by yifei-men** [comment]
Thanks for hammering on this with me on a Saturday Danny 🙇 

With the non-redacted logging of Diamond in v1.5.3, the problem is surfaced as a missing /dev/shm folder in our DNAnexus environment which Diamond assumes to exist is thus breaking (grrr... it's not very exciting of an error)

The tests have [passed](https://platform.dnanexus.com/projects/BXBXK180x0z7x5kxq11p886f/monitor/job/BxY2bq00x0z324QXxxFvkgYF) after I add a `mkdir -p /dev/shm` so we have a 1.5.3 tarball good to go know... I'll test it out with the rest of the pipelines, hopefully things will go more smoothly from here 😄 

Issue to be closed after updated resource chaining is merged to master

**Comment by yifei-men** [comment]
Closing issue, addressed by #20
