### ISSUE TITLE
demux failures silently swallowed by dnanexus

### ISSUE THREAD

**Issue by dpark01** [dnanexus/viral-ngs#47]
Looking at `job-BzVxfZj0jy1P2gG479y0qb0K`, it appears that failures during demux are not triggering failures in the DNAnexus job, even though I'm pretty sure our code emits a non-zero exit code.

**Comment by dpark01** [comment]
(this might be true in other steps too, e.g. refine1/refine2)

**Comment by yifei-men** [comment]
@mlin I didn't go hunt down the job, but I believe this is a bug I introduced >.< 

I disabled `-e` error because activating the virtualenv had a non-zero warning somewhere along the line. But this should have already been fixed by @tomkinsc earlier. So I think it should be safe to remove the `set +e +o pipefail` that you see peppered in all the apps that require activation of the viral-ngs virtualenv, like [here](https://github.com/dnanexus/viral-ngs/blob/dnanexus/viral-ngs-demux/src/viral-ngs-demux.sh#L143)

**Comment by mlin** [comment]
This should be fixed with #55 but please do reopen if it's seen again
